version: "1.0"

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    restart: always
    networks:
      - notes-app-network
    depends_on:
      - django
  db: 
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - notes-app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
  
  django:
    build:
      context: .
    container_name: django_cont
    command: sh -c "python manage.py migrate --no-input && gunicorn notes_app.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    networks:
      - notes-app-network
    restart: always
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

volumes:
  mysql_data:

networks:
  notes-app-network:
    driver: bridge